name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          cache: npm
          node-version: 20
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Run build
        run: |
          npm ci --no-audit
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: jellyfin-org__build
          path: build
      - name: Upload pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./build

  deploy:
    if: github.event_name == 'push'
    name: Deploy to GitHub Pages
    concurrency: build-deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  publish:
    if: github.repository == 'jellyfin/jellyfin.org'
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add comment
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        if: github.event_name == 'pull_request_target'
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | üîÑ Deploying... |
            | **Preview URL**   | Not available |
            | **Type**          | üîÄ Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        with:
          name: jellyfin-org__build
          path: build
      - name: Publish to Cloudflare
        id: cf
        uses: cloudflare/wrangler-action@f84a562284fc78278ff9052435d9526f9c718361 # v3.7.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=jellyfin-org --branch=${{
            (github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.full_name == github.repository)
            && (github.event.pull_request.head.ref || github.ref_name)
            || format('{0}/{1}', github.event.pull_request.head.repo.full_name, github.event.pull_request.head.ref)
            }} --commit-hash=${{ github.event.pull_request.head.sha || github.sha }}
      - name: Update status comment (Success)
        if: ${{ github.event_name == 'pull_request_target' && success() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ‚úÖ Deployed! |
            | **Preview URL**   | ${{ steps.cf.outputs.deployment-url != '' && steps.cf.outputs.deployment-url || 'Not available' }} |
            | **Type**          | üîÄ Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate
      - name: Update status comment (Failure)
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ‚ùå Failure. Check workflow logs for details |
            | **Preview URL**   | Not available |
            | **Type**          | üîÄ Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate
