name: test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-urls:
    name: Test URLs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - test:blog-urls
          - test:docs-urls
          - test:web-urls

    steps:
      - name: Check out Git repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Build and start test server
        run: |
          npm ci --no-audit
          npm run build
          npm run serve &

      - name: Test URL
        run: npm run ${{ matrix.command }}
